/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    String testReadFile = "./app/src/main/resources/quotes.json";
    @Test
    public void readFromFileTest()
    {
        try
        {
            assertEquals("Method should return the targeted quote and author from the test file.",
                    "Quotes{author='Marilyn Monroe', text=' �I am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to find someone to love.� ” ",
                    Quotes.readFromJsonFile(testReadFile));
        } catch (Exception error)
        {
            fail();
        }
    }
}
