/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import java.io.FileNotFoundException;

public class App {

    public static void main(String[] args) throws Exception {
        Quotes q = new Quotes();
        System.out.println(q.readFromJsonFile("app/src/main/resources/recentquotes.json"));


    }
}
